"""add users patient-id correction-author

Revision ID: 17d9bf28412d
Revises: a3f1c8b2d4e6
Create Date: 2026-02-12 11:05:48.915826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '17d9bf28412d'
down_revision: Union[str, Sequence[str], None] = 'a3f1c8b2d4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key('fk_corrections_username', 'users', ['username'], ['username'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Seed default user
    op.execute(
        "INSERT INTO users (username, name, email, created_at) "
        "VALUES ('talkasab', 'Tarik Alkasab', 'tarik@alkasab.org', datetime('now'))"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_corrections_username', type_='foreignkey')
        batch_op.drop_column('username')

    op.drop_table('users')
    # ### end Alembic commands ###
