"""add users patient-id correction-author

Revision ID: 17d9bf28412d
Revises: a3f1c8b2d4e6
Create Date: 2026-02-12 11:05:48.915826

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '17d9bf28412d'
down_revision: str | Sequence[str] | None = 'a3f1c8b2d4e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if "users" not in inspector.get_table_names():
        op.create_table(
            "users",
            sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column("created_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.PrimaryKeyConstraint("username"),
        )

    corrections_cols = {col["name"] for col in inspector.get_columns("corrections")}
    corrections_fks = {
        fk.get("name")
        for fk in inspector.get_foreign_keys("corrections")
        if fk.get("name") is not None
    }
    if "username" not in corrections_cols or "fk_corrections_username" not in corrections_fks:
        with op.batch_alter_table("corrections", schema=None) as batch_op:
            if "username" not in corrections_cols:
                batch_op.add_column(
                    sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
                )
            if "fk_corrections_username" not in corrections_fks:
                batch_op.create_foreign_key(
                    "fk_corrections_username",
                    "users",
                    ["username"],
                    ["username"],
                )

    reports_cols = {col["name"] for col in inspector.get_columns("reports")}
    if "patient_id" not in reports_cols:
        with op.batch_alter_table("reports", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column("patient_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
            )

    op.execute(
        "INSERT INTO users (username, name, email, created_at) "
        "SELECT 'talkasab', 'Tarik Alkasab', 'tarik@alkasab.org', datetime('now') "
        "WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'talkasab')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('corrections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_corrections_username', type_='foreignkey')
        batch_op.drop_column('username')

    op.drop_table('users')
    # ### end Alembic commands ###
